`mblog`: One common CLI for all cohorts
iterate/mikrobloggeriet pull request #18
Opened 2023-08-22 09:36 UTC by teodorlu

Jeg starter såvidt på felles CLI, med hvordan vi kan få til _konfigurasjon_ av CLI-et så det funker for alle kohorter.

2023-08-22 10:53 UTC, teodorlu commented on src/mikrobloggeriet/cli.clj
> +    (println editor)))
Jeg synes disse seks blir ganske like. Vi kunne ha skrevet en felles handler for `mblog config` og en felles handler for `mblog config set`.

Felles handler:

1. Fordel: mindre kode som er litt lik, litt ulik.
2. Ulempe: må fremdeles håndtere forskjellene mellom handlers. `:cohort` skal være et keyword. `:repo-path` skal være en mappe som finnes, som string.

Handler per config action:

1. Trenger minimalt med abstraksjon i koden.
2. Slipper conditionals i handlers - kan bruke subkommando-dispatch fra babashka.cli i stedet.

2023-08-22 13:08 UTC, teodorlu commented
@olavm - Endret CLI-et til å "være som Git".

`mblog config cohort`: leser kohort
`mblog config cohort genai`: setter kohort til å være genai.

2023-08-22 15:31 UTC, olavm approved these changes
Etter litt diskusjon synes jeg `cli-quickstart-new.md` ser bra ut nå, med utviklere som primært tiltenkt bruker. Det gir nok mest mening å tilpasse oppsett etterhvert som vi har avgjort bruken av mikrobloggeriet i større grad.
Jeg testa quickstart instruksjonene på min maskin, og det fungerte bra etterhvert. Test det gjerne du også @JohanMartinEJohnsen, og kom med en review🙌
Koden til CLIet fungerte også greit, så det blir spennende å komme i gang med implementering.

2023-08-23 08:27 UTC, JohanMartinEJohnsen approved these changes
Nice and structured code 👍

2023-08-23 08:34 UTC, JohanMartinEJohnsen requested changes
Kanskje linje 19 kunne blitt noe tydligere. Forslag til endring:

"To install the CLI with bbin, run the following command from inside the directory, meaning where you cloned down the repository:

```shell
mikrobloggeriet % bbin install . --as mblog --main-opts '["-m "mikrobloggeriet.cli"]'
```

Synes også vi kan vurdere å legge til det den returnerer om den har vært vellykket.

2023-08-23 08:57 UTC, JohanMartinEJohnsen commented
Synes også kanskje at noe av rekke følgen på readme'n kan diskuteres. Linje 33 kanskje burde komme helt til slutt etter eksempelet, og linje 43-44 burde komme etter linje 31.

2023-08-23 10:34 UTC, teodorlu commented
> Synes også vi kan vurdere å legge til det den returnerer om den har vært vellykket.

@JohanMartinEJohnsen  Tanker om hvordan vi kan gjøre det? Jeg sliter litt med å finne noe som passer.

Her er en mulighet:

> To install the CLI with bbin, run the following command from inside the directory, meaning where you cloned down the repository:
>
> ```shell
> bbin install . --as mblog --main-opts '["-m" "mikrobloggeriet.cli"]'
> ```
>
> Pay attention to the output of the command above. If it fails, you haven't installed the `mblog` CLI!

Jeg føler liksom at det er noe man må passe på _alltid_ når man installerer et CLI?

Vi kan legge det til hvis det ville hjulpet deg å skjønne hvordan du skal installere. Som nevnt er hva som bør stå i dokumentasjonen her litt i blindsonen min -- jeg kjenner verktøyene vi bruker såpass godt at jeg ikke ser alle tingene som bør dokumenteres.

2023-08-23 10:36 UTC, teodorlu commented
> Synes også kanskje at noe av rekke følgen på readme'n kan diskuteres. Linje 33 kanskje burde komme helt til slutt etter eksempelet, og linje 43-44 burde komme etter linje 31.

Godt poeng, enig.

Her er ny tekst:

> ## Configure `mblog`
> 
> `mblog` requires the following configuration for writing:
> 
> 1. Repo path: where you have cloned the `mikrobloggeriet` CLI.
> 2. User cohort: the default cohort you are writing for.
> 3. Editor: how you want to edit your text.
> 
> To configure repo path, user cohort and editor, run:
> 
>     mblog config repo-path YOUR_REPO_PATH
>     mblog config cohort YOUR_COHORT
>     mblog config editor YOUR_EDITOR
> 
> When repo-path, cohort and editor are set, you can run `mblog create` to write a new post.

2023-08-23 11:02 UTC, JohanMartinEJohnsen approved these changes

2023-08-23 11:03 UTC, teodorlu commented
Takk for feedback!

2023-08-23 11:03 UTC, merged